# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workdir

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workdir/build_arm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workdir/build_arm/CMakeFiles /workdir/build_arm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workdir/build_arm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named lvglsim

# Build rule for target.
lvglsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvglsim
.PHONY : lvglsim

# fast build rule for target.
lvglsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/build
.PHONY : lvglsim/fast

#=============================================================================
# Target rules for targets named lvgl_linux

# Build rule for target.
lvgl_linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_linux
.PHONY : lvgl_linux

# fast build rule for target.
lvgl_linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/build
.PHONY : lvgl_linux/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_demos.dir/build.make lvgl/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_examples.dir/build.make lvgl/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_thorvg

# Build rule for target.
lvgl_thorvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_thorvg
.PHONY : lvgl_thorvg

# fast build rule for target.
lvgl_thorvg/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_thorvg.dir/build.make lvgl/CMakeFiles/lvgl_thorvg.dir/build
.PHONY : lvgl_thorvg/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl.dir/build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

src/api.o: src/api.c.o

.PHONY : src/api.o

# target to build an object file
src/api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/api.c.o
.PHONY : src/api.c.o

src/api.i: src/api.c.i

.PHONY : src/api.i

# target to preprocess a source file
src/api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/api.c.i
.PHONY : src/api.c.i

src/api.s: src/api.c.s

.PHONY : src/api.s

# target to generate assembly for a file
src/api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/api.c.s
.PHONY : src/api.c.s

src/cJSON.o: src/cJSON.c.o

.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i

.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s

.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/calendar_icon.o: src/calendar_icon.c.o

.PHONY : src/calendar_icon.o

# target to build an object file
src/calendar_icon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/calendar_icon.c.o
.PHONY : src/calendar_icon.c.o

src/calendar_icon.i: src/calendar_icon.c.i

.PHONY : src/calendar_icon.i

# target to preprocess a source file
src/calendar_icon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/calendar_icon.c.i
.PHONY : src/calendar_icon.c.i

src/calendar_icon.s: src/calendar_icon.c.s

.PHONY : src/calendar_icon.s

# target to generate assembly for a file
src/calendar_icon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/calendar_icon.c.s
.PHONY : src/calendar_icon.c.s

src/config.o: src/config.c.o

.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/config.c.s
.PHONY : src/config.c.s

src/lib/display_backends/fbdev.o: src/lib/display_backends/fbdev.c.o

.PHONY : src/lib/display_backends/fbdev.o

# target to build an object file
src/lib/display_backends/fbdev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/display_backends/fbdev.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/display_backends/fbdev.c.o
.PHONY : src/lib/display_backends/fbdev.c.o

src/lib/display_backends/fbdev.i: src/lib/display_backends/fbdev.c.i

.PHONY : src/lib/display_backends/fbdev.i

# target to preprocess a source file
src/lib/display_backends/fbdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/display_backends/fbdev.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/display_backends/fbdev.c.i
.PHONY : src/lib/display_backends/fbdev.c.i

src/lib/display_backends/fbdev.s: src/lib/display_backends/fbdev.c.s

.PHONY : src/lib/display_backends/fbdev.s

# target to generate assembly for a file
src/lib/display_backends/fbdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/display_backends/fbdev.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/display_backends/fbdev.c.s
.PHONY : src/lib/display_backends/fbdev.c.s

src/lib/driver_backends.o: src/lib/driver_backends.c.o

.PHONY : src/lib/driver_backends.o

# target to build an object file
src/lib/driver_backends.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/driver_backends.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/driver_backends.c.o
.PHONY : src/lib/driver_backends.c.o

src/lib/driver_backends.i: src/lib/driver_backends.c.i

.PHONY : src/lib/driver_backends.i

# target to preprocess a source file
src/lib/driver_backends.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/driver_backends.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/driver_backends.c.i
.PHONY : src/lib/driver_backends.c.i

src/lib/driver_backends.s: src/lib/driver_backends.c.s

.PHONY : src/lib/driver_backends.s

# target to generate assembly for a file
src/lib/driver_backends.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/driver_backends.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/driver_backends.c.s
.PHONY : src/lib/driver_backends.c.s

src/lib/indev_backends/evdev.o: src/lib/indev_backends/evdev.c.o

.PHONY : src/lib/indev_backends/evdev.o

# target to build an object file
src/lib/indev_backends/evdev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/indev_backends/evdev.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/indev_backends/evdev.c.o
.PHONY : src/lib/indev_backends/evdev.c.o

src/lib/indev_backends/evdev.i: src/lib/indev_backends/evdev.c.i

.PHONY : src/lib/indev_backends/evdev.i

# target to preprocess a source file
src/lib/indev_backends/evdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/indev_backends/evdev.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/indev_backends/evdev.c.i
.PHONY : src/lib/indev_backends/evdev.c.i

src/lib/indev_backends/evdev.s: src/lib/indev_backends/evdev.c.s

.PHONY : src/lib/indev_backends/evdev.s

# target to generate assembly for a file
src/lib/indev_backends/evdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/indev_backends/evdev.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/indev_backends/evdev.c.s
.PHONY : src/lib/indev_backends/evdev.c.s

src/lib/mouse_cursor_icon.o: src/lib/mouse_cursor_icon.c.o

.PHONY : src/lib/mouse_cursor_icon.o

# target to build an object file
src/lib/mouse_cursor_icon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/mouse_cursor_icon.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/mouse_cursor_icon.c.o
.PHONY : src/lib/mouse_cursor_icon.c.o

src/lib/mouse_cursor_icon.i: src/lib/mouse_cursor_icon.c.i

.PHONY : src/lib/mouse_cursor_icon.i

# target to preprocess a source file
src/lib/mouse_cursor_icon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/mouse_cursor_icon.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/mouse_cursor_icon.c.i
.PHONY : src/lib/mouse_cursor_icon.c.i

src/lib/mouse_cursor_icon.s: src/lib/mouse_cursor_icon.c.s

.PHONY : src/lib/mouse_cursor_icon.s

# target to generate assembly for a file
src/lib/mouse_cursor_icon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/mouse_cursor_icon.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/mouse_cursor_icon.c.s
.PHONY : src/lib/mouse_cursor_icon.c.s

src/lib/simulator_util.o: src/lib/simulator_util.c.o

.PHONY : src/lib/simulator_util.o

# target to build an object file
src/lib/simulator_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/simulator_util.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/simulator_util.c.o
.PHONY : src/lib/simulator_util.c.o

src/lib/simulator_util.i: src/lib/simulator_util.c.i

.PHONY : src/lib/simulator_util.i

# target to preprocess a source file
src/lib/simulator_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/simulator_util.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/simulator_util.c.i
.PHONY : src/lib/simulator_util.c.i

src/lib/simulator_util.s: src/lib/simulator_util.c.s

.PHONY : src/lib/simulator_util.s

# target to generate assembly for a file
src/lib/simulator_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lib/simulator_util.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/simulator_util.c.s
.PHONY : src/lib/simulator_util.c.s

src/lv_font_my_montserrat_14.o: src/lv_font_my_montserrat_14.c.o

.PHONY : src/lv_font_my_montserrat_14.o

# target to build an object file
src/lv_font_my_montserrat_14.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_14.c.o
.PHONY : src/lv_font_my_montserrat_14.c.o

src/lv_font_my_montserrat_14.i: src/lv_font_my_montserrat_14.c.i

.PHONY : src/lv_font_my_montserrat_14.i

# target to preprocess a source file
src/lv_font_my_montserrat_14.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_14.c.i
.PHONY : src/lv_font_my_montserrat_14.c.i

src/lv_font_my_montserrat_14.s: src/lv_font_my_montserrat_14.c.s

.PHONY : src/lv_font_my_montserrat_14.s

# target to generate assembly for a file
src/lv_font_my_montserrat_14.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_14.c.s
.PHONY : src/lv_font_my_montserrat_14.c.s

src/lv_font_my_montserrat_20.o: src/lv_font_my_montserrat_20.c.o

.PHONY : src/lv_font_my_montserrat_20.o

# target to build an object file
src/lv_font_my_montserrat_20.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_20.c.o
.PHONY : src/lv_font_my_montserrat_20.c.o

src/lv_font_my_montserrat_20.i: src/lv_font_my_montserrat_20.c.i

.PHONY : src/lv_font_my_montserrat_20.i

# target to preprocess a source file
src/lv_font_my_montserrat_20.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_20.c.i
.PHONY : src/lv_font_my_montserrat_20.c.i

src/lv_font_my_montserrat_20.s: src/lv_font_my_montserrat_20.c.s

.PHONY : src/lv_font_my_montserrat_20.s

# target to generate assembly for a file
src/lv_font_my_montserrat_20.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/lv_font_my_montserrat_20.c.s
.PHONY : src/lv_font_my_montserrat_20.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.s
.PHONY : src/main.c.s

src/schedule_data.o: src/schedule_data.c.o

.PHONY : src/schedule_data.o

# target to build an object file
src/schedule_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_data.c.o
.PHONY : src/schedule_data.c.o

src/schedule_data.i: src/schedule_data.c.i

.PHONY : src/schedule_data.i

# target to preprocess a source file
src/schedule_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_data.c.i
.PHONY : src/schedule_data.c.i

src/schedule_data.s: src/schedule_data.c.s

.PHONY : src/schedule_data.s

# target to generate assembly for a file
src/schedule_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_data.c.s
.PHONY : src/schedule_data.c.s

src/schedule_ui.o: src/schedule_ui.c.o

.PHONY : src/schedule_ui.o

# target to build an object file
src/schedule_ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_ui.c.o
.PHONY : src/schedule_ui.c.o

src/schedule_ui.i: src/schedule_ui.c.i

.PHONY : src/schedule_ui.i

# target to preprocess a source file
src/schedule_ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_ui.c.i
.PHONY : src/schedule_ui.c.i

src/schedule_ui.s: src/schedule_ui.c.s

.PHONY : src/schedule_ui.s

# target to generate assembly for a file
src/schedule_ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/schedule_ui.c.s
.PHONY : src/schedule_ui.c.s

src/theme_icon_dark.o: src/theme_icon_dark.c.o

.PHONY : src/theme_icon_dark.o

# target to build an object file
src/theme_icon_dark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_dark.c.o
.PHONY : src/theme_icon_dark.c.o

src/theme_icon_dark.i: src/theme_icon_dark.c.i

.PHONY : src/theme_icon_dark.i

# target to preprocess a source file
src/theme_icon_dark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_dark.c.i
.PHONY : src/theme_icon_dark.c.i

src/theme_icon_dark.s: src/theme_icon_dark.c.s

.PHONY : src/theme_icon_dark.s

# target to generate assembly for a file
src/theme_icon_dark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_dark.c.s
.PHONY : src/theme_icon_dark.c.s

src/theme_icon_light.o: src/theme_icon_light.c.o

.PHONY : src/theme_icon_light.o

# target to build an object file
src/theme_icon_light.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_light.c.o
.PHONY : src/theme_icon_light.c.o

src/theme_icon_light.i: src/theme_icon_light.c.i

.PHONY : src/theme_icon_light.i

# target to preprocess a source file
src/theme_icon_light.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_light.c.i
.PHONY : src/theme_icon_light.c.i

src/theme_icon_light.s: src/theme_icon_light.c.s

.PHONY : src/theme_icon_light.s

# target to generate assembly for a file
src/theme_icon_light.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/theme_icon_light.c.s
.PHONY : src/theme_icon_light.c.s

src/time_date_display.o: src/time_date_display.c.o

.PHONY : src/time_date_display.o

# target to build an object file
src/time_date_display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/time_date_display.c.o
.PHONY : src/time_date_display.c.o

src/time_date_display.i: src/time_date_display.c.i

.PHONY : src/time_date_display.i

# target to preprocess a source file
src/time_date_display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/time_date_display.c.i
.PHONY : src/time_date_display.c.i

src/time_date_display.s: src/time_date_display.c.s

.PHONY : src/time_date_display.s

# target to generate assembly for a file
src/time_date_display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/time_date_display.c.s
.PHONY : src/time_date_display.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... lvgl"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... lvgl_linux"
	@echo "... lvgl_thorvg"
	@echo "... lvglsim"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/calendar_icon.o"
	@echo "... src/calendar_icon.i"
	@echo "... src/calendar_icon.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/lib/display_backends/fbdev.o"
	@echo "... src/lib/display_backends/fbdev.i"
	@echo "... src/lib/display_backends/fbdev.s"
	@echo "... src/lib/driver_backends.o"
	@echo "... src/lib/driver_backends.i"
	@echo "... src/lib/driver_backends.s"
	@echo "... src/lib/indev_backends/evdev.o"
	@echo "... src/lib/indev_backends/evdev.i"
	@echo "... src/lib/indev_backends/evdev.s"
	@echo "... src/lib/mouse_cursor_icon.o"
	@echo "... src/lib/mouse_cursor_icon.i"
	@echo "... src/lib/mouse_cursor_icon.s"
	@echo "... src/lib/simulator_util.o"
	@echo "... src/lib/simulator_util.i"
	@echo "... src/lib/simulator_util.s"
	@echo "... src/lv_font_my_montserrat_14.o"
	@echo "... src/lv_font_my_montserrat_14.i"
	@echo "... src/lv_font_my_montserrat_14.s"
	@echo "... src/lv_font_my_montserrat_20.o"
	@echo "... src/lv_font_my_montserrat_20.i"
	@echo "... src/lv_font_my_montserrat_20.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/schedule_data.o"
	@echo "... src/schedule_data.i"
	@echo "... src/schedule_data.s"
	@echo "... src/schedule_ui.o"
	@echo "... src/schedule_ui.i"
	@echo "... src/schedule_ui.s"
	@echo "... src/theme_icon_dark.o"
	@echo "... src/theme_icon_dark.i"
	@echo "... src/theme_icon_dark.s"
	@echo "... src/theme_icon_light.o"
	@echo "... src/theme_icon_light.i"
	@echo "... src/theme_icon_light.s"
	@echo "... src/time_date_display.o"
	@echo "... src/time_date_display.i"
	@echo "... src/time_date_display.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

